/* ipoque GmbH
 * info@ipoque.com
 */

#ifndef __IPOQUE_API_INCLUDE_FILE__
#error CANNOT INCLUDE THIS .H FILE, INCLUDE IPQ_API.H
#endif

#ifndef IPQ_CONFIG_H
#define IPQ_CONFIG_H

#undef IPOQUE_PACE_API_MK1
#define IPOQUE_PACE_API_MK2

//#define IPOQUE_ENABLE_LICENSING
//#define IPOQUE_KERNEL_UPDATE_MODULE
//#define IPOQUE_DEMO_VERSION

#define IPOQUE_SUPPORT_OS_DETECTION
#define IPOQUE_SUPPORT_FLOW_ID_CORRELATION
#define IPOQUE_MEASURE_RTP_PERFORMANCE

#endif /* IPQ_CONFIG_H */
