/*
 * pcp_limits.hpp
 *
 *  Created on: 20 May 2013
 *      Author: ezhelao
 */

#ifndef PCP_LIMITS_HPP_
#define PCP_LIMITS_HPP_
// IWD defined max and min sizes
#define MAX_GTPU_FLOW_LENGTH 2000
#define MAX_HOST_NAME_SIZE 128
#define MAX_CONTENT_TYPE_SIZE 256
#define MAX_CLIENT_TYPE_SIZE 40
#define MAX_USER_AGENT_LENGTH 1000
#define MIN_URI_EXTENSION_LENGTH 2
#define MAX_URI_EXTENSION_LENGTH 10
#define MIN_DATA_RECEIVED_PER_PACKET 0
#define MAX_DATA_DECEIVED_PER_PACKET USHRT_MAX
#define MIN_THROUGHPUT 0
#define MAX_THROUGHPUT ULONG_MAX // 2^64-1
#define MAX_RTT_STRING_LENGTH 32
#define MAX_PKT_LOSS_STRING_LENGTH 10
#define MAX_SUB_PROTOCOL_STRING_LENGTH 100
#define MAX_APPLICATION_STRING_LENGTH 100
#define MAX_IPOQUE_PROTOCOL_STRING_LENGTH 100
#define MAX_IPOQUE_GROUP_STRING_LENGTH 100
#define IPOQUE_MAX_HTTP_CUSTOM_PROTOCOLS 7
#endif /* PCP_LIMITS_HPP_ */
