#!/bin/expect
;# Author: elukpot

set timeout -1

;# -- command line arguments to our scripts
set server [lindex $argv 0]
set password [lindex $argv 1]

;# shell prompt character
set prompt "# "

;# -- main procecure 
proc dostuff {} {
	send -- "mkdir /tmp/output/;mkdir /tmp/tmp/;chmod 777 /tmp/output/ /tmp/tmp/;cd /tmp;./pect_unit_tests;chmod 777 test_results.xml;sed -i 's/&/&amp;/g' test_results.xml \r"
	return
}

;# script start running here
spawn /usr/bin/ssh $server

;# loops forever until we get a shell prompt

while (1) {

	expect {
		;# -- This is the prompt when you first use
		;# -- ssh that says "Are you sure you want to continue ..."

		"no)? " {
			send -- "yes\r"
		}

		;# -- the prompt for password
		"password: " {
			send -- "$password\r"
		}

		;# -- and finally we got a shell prompt
		"$prompt" {
			dostuff
			break
		}
	}
}

;# -- exit
expect "$prompt"
send -- "exit\r"

expect eof
