#!/bin/expect
;# Author: elukpot

set timeout -1
set files_to_collect [lindex $argv 0]
set server [lindex $argv 1]
set password [lindex $argv 2]

;# shell prompt character
set prompt "# "

;# script start running here
spawn bash -c "scp $server:\"$files_to_collect\" ./"

;# loops forever until we get a shell prompt

while (1) {

	expect {
		;# -- This is the prompt when you first use
		;# -- ssh that says "Are you sure you want to continue ..."

		"no)? " {
			send -- "yes\r"
		}

		;# -- the prompt for password
		"password: " {
			send -- "$password\r"
		}
		
		;# -- and finally we got a shell prompt
		"$prompt" {
			break
		}
	}
}

expect eof
